### ISSUE TITLE
Bug en NTP - variable no inicializada -

### ISSUE THREAD

**Issue by smarichal** [brico-labs/Oshwi_Badge_2017#5]
Tanto el fichero ESP_NTP.ino como en Clock.cpp la variable `int cp;` no está inicializada. Esto genera un comportamiento aleatorio, por ejemplo en Clock.cpp: 
 `int cb;
 while((unsigned long)(millis() - startTime) < NTP_TIMEOUT && !cb)
    cb = udp.parsePacket();

if (!cb)
  {
    Serial.println("WARNING: Unable to obtain updated time from NTP Server.");
    return false;
  }
  udp.read(packetBuffer, NTP_PACKET_SIZE); // read the packet into the buffer
  udp.stop();`
A veces se hace upd.read de paquetes defectuosos lo cuál deriva en la obtención de una fecha erronea. 

Inicializando la variable se soluciona el error. `int cb = 0;`

**Comment by 4m1g0** [comment]
Muchisimas gracias por el reporte!!

Efectivamente es un error bastante grave y que además he arrastrado en bastantes proyectos sin darme cuenta...

Lo he corregudo también en el proyecto original: https://github.com/4m1g0/IOT_tfg/commit/1d658e2b68de3ae33b37c449cb573be3452f3485

Gracias nuevamente

**Comment by smarichal** [comment]
Por nada!!!

Estaba intentando sincronizar 2 esp8266 y a veces funcionaba y a veces no.
En particular, cuando no se procesaba la respuesta del servidor ntp
correctamente la fecha que devuelve la función es 2036-02-07 06:28:16,
corresponde a la fecha que se forma cuando uno de los paquetes de respuesta
viene vacío... esto lo encontré en este thread:
https://forum.arduino.cc/index.php?topic=92632.0

Saludos!!

**Comment by 4m1g0** [comment]
Muy interesante la explicación, creo que tengo algún log por ahi con esa fecha... je je

Ya que estamos en materia, hace tiempo había estado revisando los posibles errores devueltos por un servidor NTP y según el RFC https://tools.ietf.org/html/rfc5905 sección 7.3 los 2 primeros bits de la cabecera si están a 11 indicaría un `warning: unknown (clock unsynchronized).`

Quizás no está demás comprobarlos también, y desechar esa respuesta por precaución. https://github.com/brico-labs/Oshwi_Badge_2017/commit/25f68f3cadc140485e78994e1b83ee0a4a8454ff

¿Tiene sentido?

**Comment by smarichal** [comment]
Tiene sentido!! Estaría bien comprobar para salir de la duda si cuando
devuelve la fecha 2036-02-07 06:28:16 estos dos bits están en 11. De todas
maneras la comprobación que has añadido está bien!!!

**Comment by smarichal** [comment]
Hola,

Te adjunto una versión de Clock.h con los operadores <, <=, >, >=, + y -
para el struct secodsWithTime (que habría que cambiarle el nombre porque le
falta una n a seconds jejej). Quería aprovechar y preguntarte,
por que almacenar los milisegundos en una variable separada? Es porque sino
el unsigned long que almacena los segundos se desbordaría?

Saludos!
